[[Xorg_libXpm]]
arch = "aarch64"
git-tree-sha1 = "af1767067dbf805e7db3b5304d62ec92bf6d2375"
libc = "glibc"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "54cf1aaef07afeb9cd6f819dc3fffa70350ac8e7745743faf6afc8d43ae4a304"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.17+0/Xorg_libXpm.v3.5.17.aarch64-linux-gnu.tar.gz"
[[Xorg_libXpm]]
arch = "aarch64"
git-tree-sha1 = "e24e7e491fa87f9bbb2e9aab1bc13b70afdf9d34"
libc = "musl"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "a4ec9c0e637e0732d3fdd908d17866487600cdd3b20848b0bea4445da0f179b1"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.17+0/Xorg_libXpm.v3.5.17.aarch64-linux-musl.tar.gz"
[[Xorg_libXpm]]
arch = "aarch64"
git-tree-sha1 = "d5892c8cf236be4eaa7b581341d73dc9ee21b950"
os = "freebsd"

    [[Xorg_libXpm.download]]
    sha256 = "248793269dbfecb18547f056e2e00563cd3108a3b70ad20e5d4e4f96a7e06559"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.17+0/Xorg_libXpm.v3.5.17.aarch64-unknown-freebsd.tar.gz"
[[Xorg_libXpm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2f012be197fdaf165605d70002dd0dc7691de067"
libc = "glibc"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "84bfbf819c067b253e39d4b4fa55044f82fa7610e74a4d2d52e3c472b96737f0"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.17+0/Xorg_libXpm.v3.5.17.armv6l-linux-gnueabihf.tar.gz"
[[Xorg_libXpm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9fd9a6a324964c2fbef0eda34966c51335fac4c4"
libc = "musl"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "54622c73ecd539efb431d8263378b966f9d0d6f21ba3c0f6e24ae13ebbbd355d"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.17+0/Xorg_libXpm.v3.5.17.armv6l-linux-musleabihf.tar.gz"
[[Xorg_libXpm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "67dc175bfbbb3f68d417308d5fe836803c9675b9"
libc = "glibc"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "65e9f541dc0c54537332fda152c899ae273bae10dbe0e12559b96844669866ab"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.17+0/Xorg_libXpm.v3.5.17.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libXpm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "36b15e1424cbf397aade31a44d627160db29139f"
libc = "musl"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "7e0b2232dcf2e97acf0e1e1fbe45128799f070bffc0ce1e0c745ca9d6b0354e4"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.17+0/Xorg_libXpm.v3.5.17.armv7l-linux-musleabihf.tar.gz"
[[Xorg_libXpm]]
arch = "i686"
git-tree-sha1 = "de1b72645a2567320a1ed6d9e43d14afc1ef2bc4"
libc = "glibc"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "8389b967bb22503c6e262df0383c67a879019183ee7e667677c7263af7b3e19f"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.17+0/Xorg_libXpm.v3.5.17.i686-linux-gnu.tar.gz"
[[Xorg_libXpm]]
arch = "i686"
git-tree-sha1 = "0b3e737f182db4a864aa7dd7068572b8082fec44"
libc = "musl"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "881cac38adb1bb648f3821b3a523574d4ab7ba853dfc942dfc78821ab79b85ac"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.17+0/Xorg_libXpm.v3.5.17.i686-linux-musl.tar.gz"
[[Xorg_libXpm]]
arch = "powerpc64le"
git-tree-sha1 = "8ac84f2284f10746b9577b4934cb45eb45516b26"
libc = "glibc"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "abc08d63fbf665faceab4782506908f1435c6594ac182f685c4777cc59921a34"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.17+0/Xorg_libXpm.v3.5.17.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libXpm]]
arch = "riscv64"
git-tree-sha1 = "f8deb260c8a1c3a97ae66cb1fddd68e9d51eae48"
libc = "glibc"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "9befc6494fa3646a1ef82afdd4056329d6677a5128d638bbb6bc0adf8d29bcc7"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.17+0/Xorg_libXpm.v3.5.17.riscv64-linux-gnu.tar.gz"
[[Xorg_libXpm]]
arch = "x86_64"
git-tree-sha1 = "a24ca4934d27e04c5f50358126a49c4c9ecc6671"
libc = "glibc"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "a01f3dabbc6adb535d6c15408b065b183b5319b58c3c9ed1d66e9d1ce8928e53"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.17+0/Xorg_libXpm.v3.5.17.x86_64-linux-gnu.tar.gz"
[[Xorg_libXpm]]
arch = "x86_64"
git-tree-sha1 = "a94c5f29b843575aeb7e4bab1d8833e4acfc4f14"
libc = "musl"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "8494397ed3be3a54bbb88fb5fab9b6318f033e9e81b3c77385eda5d5d95317a2"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.17+0/Xorg_libXpm.v3.5.17.x86_64-linux-musl.tar.gz"
[[Xorg_libXpm]]
arch = "x86_64"
git-tree-sha1 = "dce667fa3570ac49f76926b24b618680160f7521"
os = "freebsd"

    [[Xorg_libXpm.download]]
    sha256 = "052a3e143933640be9d8c70427771e22c6e6cd3943f8dc6c895abb1f0e73f2c1"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.17+0/Xorg_libXpm.v3.5.17.x86_64-unknown-freebsd.tar.gz"
