[[Xorg_libXpm]]
arch = "aarch64"
git-tree-sha1 = "405faebd78f213cde68492a98b4f15b36292dd36"
libc = "musl"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "fd2097e5602093110b58de79b9648adc4ab324e07e39ffe4498bcd4ae4224035"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.13+1/Xorg_libXpm.v3.5.13.aarch64-linux-musl.tar.gz"
[[Xorg_libXpm]]
arch = "aarch64"
git-tree-sha1 = "fe3800aefd0d81410fbdbd882b14affb1fa77eeb"
libc = "glibc"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "427d4aa5298296b4edee7677915ade7d4195760162843de856a8957012356d44"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.13+1/Xorg_libXpm.v3.5.13.aarch64-linux-gnu.tar.gz"
[[Xorg_libXpm]]
arch = "x86_64"
git-tree-sha1 = "f39fb068728fc192a36e331c95e6fc796ce7a843"
libc = "glibc"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "561e269ced3997607607eff75ba199264f36d47f362e5d217155d8472593b133"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.13+1/Xorg_libXpm.v3.5.13.x86_64-linux-gnu.tar.gz"
[[Xorg_libXpm]]
arch = "powerpc64le"
git-tree-sha1 = "f0374c6ca8bde56960662a75c91e875bf69bc453"
libc = "glibc"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "48015a3c17c6631cbd3fb914e5e036616389b5df29cab3815d0e332ddffb06e3"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.13+1/Xorg_libXpm.v3.5.13.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libXpm]]
arch = "x86_64"
git-tree-sha1 = "00fb374b8adfde7ae40f03997ead62b7dc7c5e91"
os = "freebsd"

    [[Xorg_libXpm.download]]
    sha256 = "b533b240f3a514b002b5874593c53f95ccb96395ca744d946d492b718050b221"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.13+1/Xorg_libXpm.v3.5.13.x86_64-unknown-freebsd11.1.tar.gz"
[[Xorg_libXpm]]
arch = "i686"
git-tree-sha1 = "2efb7517473e53582f2bd938db90d451b55701fb"
libc = "glibc"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "20f8ecbf280bfa93c8629dff666c392396fbb827415376f60f1310b4d9cb5603"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.13+1/Xorg_libXpm.v3.5.13.i686-linux-gnu.tar.gz"
[[Xorg_libXpm]]
arch = "i686"
git-tree-sha1 = "61d683a84bdbcd51680a171b3bde5e529e4572b8"
libc = "musl"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "dd62afcc9a7c8b48efcecd7d38db456e0dc6c735d53fef4ebe96558e403f8c60"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.13+1/Xorg_libXpm.v3.5.13.i686-linux-musl.tar.gz"
[[Xorg_libXpm]]
arch = "armv7l"
git-tree-sha1 = "001c2c2cf04cd8394bab050c5004be06f9d6bd8c"
libc = "glibc"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "8f3f8930c0aba8a3a1eda8cca4280b725486e666c8db64d4e80a924c76878e06"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.13+1/Xorg_libXpm.v3.5.13.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libXpm]]
arch = "x86_64"
git-tree-sha1 = "e2825eeb0651d194d041ba5f8508da4cd5cf05d3"
libc = "musl"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "94b0ff2ea25f99b7c7871e740d04abc7bd367aab48b88bb2deb7d979cbfd4bbe"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.13+1/Xorg_libXpm.v3.5.13.x86_64-linux-musl.tar.gz"
[[Xorg_libXpm]]
arch = "armv7l"
git-tree-sha1 = "490d9aafe3d325100a4e3ef0ee0960e4d048aa78"
libc = "musl"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "961fc6d7a3c11cbd15a243cd01604dd00787cc03577bcd52557015c8601f575f"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.13+1/Xorg_libXpm.v3.5.13.armv7l-linux-musleabihf.tar.gz"
