[[Xorg_libXpm]]
arch = "armv7l"
git-tree-sha1 = "87235fdf55bbf63879442e13a700403a35a88844"
libc = "glibc"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "b0ccacbce27dcac995942621732fec1d60c6d0b0260400190951159a3fff55f5"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.13+0/Xorg_libXpm.v3.5.13.arm-linux-gnueabihf.tar.gz"
[[Xorg_libXpm]]
arch = "x86_64"
git-tree-sha1 = "a6a83272e470d5fd1d5d0f49c0884d972634724f"
libc = "glibc"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "dfe9241ea366a36badeaed8807ad00644d422c9d0a1742adecdc97addebb3b48"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.13+0/Xorg_libXpm.v3.5.13.x86_64-linux-gnu.tar.gz"
[[Xorg_libXpm]]
arch = "aarch64"
git-tree-sha1 = "ba0f2bf234efd45903aff2b0c708e7f3ed06f395"
libc = "glibc"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "ea61b3b554c464aaf09de820592e659b93faa5bc0d255a95bb614f3cb073ffd5"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.13+0/Xorg_libXpm.v3.5.13.aarch64-linux-gnu.tar.gz"
[[Xorg_libXpm]]
arch = "i686"
git-tree-sha1 = "2d7d2fbd239e1de20a9a7c3d3ebc2551421b75f1"
libc = "musl"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "1a8f31409a7b6c3852723897e2f13d76df6b282abfe4763b39d0c55a0d522941"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.13+0/Xorg_libXpm.v3.5.13.i686-linux-musl.tar.gz"
[[Xorg_libXpm]]
arch = "aarch64"
git-tree-sha1 = "998b68db15c477ec3e61fd7e2b4596d8d88afd43"
libc = "musl"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "65f803a1ccd43b590b3872f8de27c5c011820c874a6ee387b2b13aa3a29272ea"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.13+0/Xorg_libXpm.v3.5.13.aarch64-linux-musl.tar.gz"
[[Xorg_libXpm]]
arch = "x86_64"
git-tree-sha1 = "2609dfb49bbeb506d8409ddee50f15b61e427acf"
os = "freebsd"

    [[Xorg_libXpm.download]]
    sha256 = "e915d1e488574ad2ac521a75eb05f149bdce82a5ba7dec1b915137d7d93567c9"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.13+0/Xorg_libXpm.v3.5.13.x86_64-unknown-freebsd11.1.tar.gz"
[[Xorg_libXpm]]
arch = "powerpc64le"
git-tree-sha1 = "d75b7d72959ef37dc1f07e1b4caa3df7aa9c5aa2"
libc = "glibc"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "fb99760403b1b8def0730d54bc0a8f02a5e2adf65cc86a439d75eaf26a58d974"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.13+0/Xorg_libXpm.v3.5.13.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libXpm]]
arch = "i686"
git-tree-sha1 = "45af63f233812a71c24ca75e3c284fcdfaf3af32"
libc = "glibc"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "96ce7fb462119f7aa379f4342cbda3b2f780c0748686b5db2e6fa6bac945bac4"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.13+0/Xorg_libXpm.v3.5.13.i686-linux-gnu.tar.gz"
[[Xorg_libXpm]]
arch = "x86_64"
git-tree-sha1 = "a84830bcdf640c842da6152b51bedcc17bb4fb89"
libc = "musl"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "516f626ae1ebe396580ca360a19d580c7b863fb5d4989c3beb4d6f7051380912"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.13+0/Xorg_libXpm.v3.5.13.x86_64-linux-musl.tar.gz"
[[Xorg_libXpm]]
arch = "armv7l"
git-tree-sha1 = "7ed48d7b234a4839d757e95e50351e6ac77861af"
libc = "musl"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "e944a524b84af4fbd73b846ff196e4230f88e1ca5575b02b60c8cf4f733fb6d8"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.13+0/Xorg_libXpm.v3.5.13.arm-linux-musleabihf.tar.gz"
