[[Xorg_libXpm]]
arch = "aarch64"
git-tree-sha1 = "df2867e5a503f7b866de37b30894341e4d9da2b8"
libc = "glibc"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "e776f86d4abb92c6ab8262a47528201cef1cdb5726191f63b9df1d47d9915fea"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.19+0/Xorg_libXpm.v3.5.19.aarch64-linux-gnu.tar.gz"
[[Xorg_libXpm]]
arch = "aarch64"
git-tree-sha1 = "90e3b28072814ed45989f5c6894d300da554d3cc"
libc = "musl"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "13963ddb3328f30df956e6f9d92c66ef29747edad01462bd47c6fea698f440f9"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.19+0/Xorg_libXpm.v3.5.19.aarch64-linux-musl.tar.gz"
[[Xorg_libXpm]]
arch = "aarch64"
git-tree-sha1 = "a883818f90f8eb5f78461658ead5ac406041e0f0"
os = "freebsd"

    [[Xorg_libXpm.download]]
    sha256 = "b62529513b62e93958bfaf3e0390bd0329bb4f67647584f1a658794e31e51802"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.19+0/Xorg_libXpm.v3.5.19.aarch64-unknown-freebsd.tar.gz"
[[Xorg_libXpm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ffd8ff6bc108f9d8f35eece6a1657dcb54ca9f2c"
libc = "glibc"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "44dfe3569cb7fc7e5db02edca20e09017c73258861a9182a2d60ac9e8181aad3"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.19+0/Xorg_libXpm.v3.5.19.armv6l-linux-gnueabihf.tar.gz"
[[Xorg_libXpm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6075b00be5f2eee40b56ffd1dbbe50645926a28c"
libc = "musl"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "3dd5c36c6e2754a554399f120a9dd88dc9ade83cc15733621035e3919c4854db"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.19+0/Xorg_libXpm.v3.5.19.armv6l-linux-musleabihf.tar.gz"
[[Xorg_libXpm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "75854c5f36f56ba66d7ccdcc23d67b84c5165b66"
libc = "glibc"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "400b1fd811c06d85d26adc555744b49f2ebddb40b1258062dd2c1cb339b79969"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.19+0/Xorg_libXpm.v3.5.19.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libXpm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0f34807599d0fca41638d1b77a2d2ee4b6cb4b1b"
libc = "musl"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "289cf5bdc8b10708f4ed4d368de2012cb40ca6f621230df2ac089eaef1717778"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.19+0/Xorg_libXpm.v3.5.19.armv7l-linux-musleabihf.tar.gz"
[[Xorg_libXpm]]
arch = "i686"
git-tree-sha1 = "c7fa580a84a472371aca2ac96e735bde4ece446d"
libc = "glibc"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "3faf86b18ad89da495ef0ddad9338e781c389043466fe11c9e4d17d15aca2101"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.19+0/Xorg_libXpm.v3.5.19.i686-linux-gnu.tar.gz"
[[Xorg_libXpm]]
arch = "i686"
git-tree-sha1 = "c708911795918d0f500d813d76ee866d605053e5"
libc = "musl"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "327500c9498d3e46323d8a366c0e91f8d663ee58ed6011fd3a9381ce1f387443"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.19+0/Xorg_libXpm.v3.5.19.i686-linux-musl.tar.gz"
[[Xorg_libXpm]]
arch = "powerpc64le"
git-tree-sha1 = "cd0ad9f5e4ef47eba74df5308fb77f6bedcd198c"
libc = "glibc"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "21a386961892b5f3c8cbc36f826c4352f79853e8df8d49909c77a77d868cbff7"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.19+0/Xorg_libXpm.v3.5.19.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libXpm]]
arch = "riscv64"
git-tree-sha1 = "4611fd8d7624a9f25e941d7d3fede1b6c2a8499b"
libc = "glibc"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "3f19ee38ff46aef53a712bd50e3a8d7f6f87e1210b3f6edddbea1951fb69944a"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.19+0/Xorg_libXpm.v3.5.19.riscv64-linux-gnu.tar.gz"
[[Xorg_libXpm]]
arch = "x86_64"
git-tree-sha1 = "88e037b633380e9b762050c44fa920b806534ea4"
libc = "glibc"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "6df733112c8860aff7a4e7cab088e0ad8563dbd5c64c3d2674423fa6f0448550"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.19+0/Xorg_libXpm.v3.5.19.x86_64-linux-gnu.tar.gz"
[[Xorg_libXpm]]
arch = "x86_64"
git-tree-sha1 = "9582d560d7b5058e55c7f0f76b7d61e0472dbcd2"
libc = "musl"
os = "linux"

    [[Xorg_libXpm.download]]
    sha256 = "fa734698619070aa8df5aa74365b2d6e1e964469b5d7b4144b3d71e701104890"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.19+0/Xorg_libXpm.v3.5.19.x86_64-linux-musl.tar.gz"
[[Xorg_libXpm]]
arch = "x86_64"
git-tree-sha1 = "6cd62ffcf7e352bcc649abf2c6e4504a6a1b06dc"
os = "freebsd"

    [[Xorg_libXpm.download]]
    sha256 = "65272eab9adca5ba6f9eb4e7f2e01bfcc001c79567a871ee5e6beabcf42b70d0"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXpm_jll.jl/releases/download/Xorg_libXpm-v3.5.19+0/Xorg_libXpm.v3.5.19.x86_64-unknown-freebsd.tar.gz"
