# Autogenerated wrapper script for Xorg_libXpm_jll for x86_64-linux-gnu
export libXpm

using Xorg_libX11_jll
JLLWrappers.@generate_wrapper_header("Xorg_libXpm")
JLLWrappers.@declare_library_product(libXpm, "libXpm.so.4")
function __init__()
    JLLWrappers.@generate_init_header(Xorg_libX11_jll)
    JLLWrappers.@init_library_product(
        libXpm,
        "lib/libXpm.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
